### ISSUE TITLE
Failed to compile normalization.Rmd

### ISSUE THREAD

**Issue by mdozmorov** [lmweber/OSTA-base#1]
A few prerequisites:

````
devtools::install_github("LTLA/rebook")
devtools::install_github("lmweber/STdata")
BiocManager::install("scater")
devtools::install_github("lmweber/spatzli")
BiocManager::install("scran")
````

Still, the compilation breaks at:

````
Quitting from lines 26-44 (normalization.Rmd) 
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions
Calls: local ... librarySizeFactors -> .local -> colSums -> colSums -> <Anonymous>

Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile normalization.Rmd
````

Thanks, @lmweber, looking forward to working through the book.

**Comment by lmweber** [comment]
Thanks for mentioning this. I have updated the readme to include the additional prerequisites and some more detailed compilation instructions.

I tried it again just now in a new directory on my computer, and it seemed to work.

One thing I noticed is that it seems to work better if I use RStudio. (When I tried compiling it outside RStudio, I got some errors about `pandoc`.) I have added this to the readme instructions now. Are you using RStudio?

I don't think I had any errors like yours recently. Do you have the latest version of R and Bioconductor?

**Comment by mdozmorov** [comment]
Thanks, Lukas. Yes, I'm using RStudio, R 4.0.2, and Bioconductor 3.11. 

It was necessary to delete cache and intermediate directories, like `rm -r _bookdown_files/ human_DLPFC_cache/ human_DLPFC_files/`. Then, it advances much further, after installing another dependency: `install.packages("uwot")`

The error below is because the latest `scran` version seems to drop the `use.dimred = "PCA"` argument. It is still in the help, but not in the function definition. Just removing it (and deleting cache for this page), doesn't help. 

````
Quitting from lines 32-44 (clustering.Rmd) 
Error in .local(x, ...) : unused argument (use.dimred = "PCA")
Calls: local ... withVisible -> eval -> eval -> buildSNNGraph -> buildSNNGraph

Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile clustering.Rmd
````

**Comment by lmweber** [comment]
Oh cool, thanks for finding that. I will check what I have done with this `use.dimred` argument. Maybe I had an older version of `scran` loaded.

Yes deleting all the cache folders sometimes can help too, if something has gone wrong.

**Comment by lmweber** [comment]
Hmm strange. I have `scran 1.16.0` and `scater 1.16.1`, and when I check `getMethod(buildSNNGraph, "SingleCellExperiment")` it still seems to show the `use.dimred` argument being used as expected.

Maybe it is a different problem. I will do some more investigating to see if I can reproduce the error. In the meantime, possibly worth deleting all the cache files/folders and/or re-cloning the repo and starting over too.

**Comment by mdozmorov** [comment]
It worked. I believe, the problem was that the `pheatmap` package was missing. I noted it when recompiling. After installing, the book renders perfectly.

`pheatmap` is already in the prerequisites, so others shouldn't have issues if they follow the instructions. Closing this issue as resolved. Thank you, Lukas

**Comment by lmweber** [comment]
Ah great, thanks for letting me know!
